version: '3.8'

services:
  homeassistant:
    container_name: homeassistant-test
    image: homeassistant/home-assistant:latest
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Asia/Kuala_Lumpur 