refresh_prayer_times:
  name: Refresh Prayer Times
  description: Manually refresh prayer times data
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID of the prayer time sensor to refresh
      required: false
      example: "sensor.waktu_solat_malaysia"
      selector:
        entity:
          domain: sensor
          integration: solatsyncmy

play_azan:
  name: Play Azan
  description: Play azan for a specific prayer time
  fields:
    prayer:
      name: Prayer
      description: Which prayer's azan to play
      required: true
      selector:
        select:
          options:
            - value: "fajr"
              label: "Subuh"
            - value: "dhuhr" 
              label: "Zohor"
            - value: "asr"
              label: "Asar"
            - value: "maghrib"
              label: "Maghrib"
            - value: "isha"
              label: "Isyak"
    media_player:
      name: Media Player
      description: Media player entity to use for playback
      required: true
      selector:
        entity:
          domain: media_player
    volume:
      name: Volume
      description: Volume level for playback (0.1-1.0)
      required: false
      default: 0.7
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
          mode: slider

test_audio:
  name: Test Audio Playback
  description: Test audio playback with detailed diagnostics and troubleshooting
  fields:
    media_player:
      name: Media Player
      description: Media player entity to test
      required: true
      selector:
        entity:
          domain: media_player
    audio_file:
      name: Audio File
      description: Audio file to test
      required: false
      default: "azan.mp3"
      selector:
        select:
          options:
            - value: "azan.mp3"
              label: "Normal Azan (Zohor, Asar, Maghrib, Isyak)"
            - value: "azanfajr.mp3"
              label: "Subuh Azan"
    volume:
      name: Volume
      description: Test volume level (0.1-1.0)
      required: false
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
          mode: slider 