refresh_prayer_times:
  name: Refresh Prayer Times
  description: Manually refresh prayer times data
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID of the prayer time sensor to refresh
      required: false
      selector:
        entity:
          domain: sensor
          integration: waktu_solat_malaysia

play_azan:
  name: Play Azan
  description: Manually play azan for a specific prayer
  fields:
    prayer:
      name: Prayer
      description: Which prayer's azan to play
      required: true
      selector:
        select:
          options:
            - fajr
            - dhuhr
            - asr
            - maghrib
            - isha
    media_player:
      name: Media Player
      description: Media player to use for azan playback
      required: false
      selector:
        entity:
          domain: media_player
    volume:
      name: Volume
      description: Volume level for azan playback (0.1 - 1.0)
      required: false
      default: 0.7
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
          mode: slider 