refresh_prayer_times:
  name: Refresh Prayer Times
  description: Manually refresh prayer times data
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID of the prayer time sensor to refresh
      required: false
      example: "sensor.waktu_solat_malaysia"
      selector:
        entity:
          domain: sensor
          integration: solatsyncmy

play_azan:
  name: Play Azan
  description: Play the azan (call to prayer) audio on a specified media player
  fields:
    prayer:
      name: Prayer
      description: The prayer time (fajr, dhuhr, asr, maghrib, isha)
      required: true
      example: "maghrib"
      selector:
        select:
          options:
            - fajr
            - dhuhr
            - asr
            - maghrib
            - isha
    media_player:
      name: Media Player
      description: The entity ID of the media player to use
      required: true
      example: "media_player.living_room_speaker"
      selector:
        entity:
          domain: media_player
    volume:
      name: Volume
      description: The volume level (0.0 to 1.0)
      required: false
      default: 0.5
      example: 0.7
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.1

test_audio:
  name: Test Audio Playback
  description: Test audio playback on a media player with detailed debugging
  fields:
    media_player:
      name: Media Player
      description: The entity ID of the media player to test
      required: true
      example: "media_player.living_room_speaker"
      selector:
        entity:
          domain: media_player
    audio_file:
      name: Audio File
      description: The audio file to test (default azan.mp3)
      required: false
      default: "azan.mp3"
      example: "azan.mp3"
      selector:
        text:
    volume:
      name: Volume
      description: The volume level (0.0 to 1.0)
      required: false
      default: 0.5
      example: 0.7
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.1 